// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOmP7Qa4HXh8z0JiTn43mLNTV4pqZbKb8',
    appId: '1:752316268712:android:8693130b5cdc065660c29d',
    messagingSenderId: '752316268712',
    projectId: 'equigro-cb4bd',
    databaseURL: 'https://equigro-cb4bd.firebaseio.com',
    storageBucket: 'equigro-cb4bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqOR_uEF1rD-Ys0vTLn9gfKrhmbZidjRg',
    appId: '1:752316268712:ios:a96c0be9ce87d42260c29d',
    messagingSenderId: '752316268712',
    projectId: 'equigro-cb4bd',
    databaseURL: 'https://equigro-cb4bd.firebaseio.com',
    storageBucket: 'equigro-cb4bd.appspot.com',
    androidClientId: '752316268712-922j9c4prudm0a7ldrunv27adpjp772p.apps.googleusercontent.com',
    iosClientId: '752316268712-cpf11u0kd499bpg1ko915lirjl6kdglf.apps.googleusercontent.com',
    iosBundleId: 'com.blueprint-mobile.app',
  );
}
