/// Flutter icons BlueprintTrade
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BlueprintTrade
///      fonts:
///       - asset: fonts/BlueprintTrade.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BlueprintTrade {
  BlueprintTrade._();

  static const _kFontFam = 'BlueprintTrade';
  static const _kFontPkg = null;

  static const IconData trade = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
