/// Flutter icons BluePrintProfile
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BluePrintProfile
///      fonts:
///       - asset: fonts/BluePrintProfile.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BluePrintProfile {
  BluePrintProfile._();

  static const _kFontFam = 'BluePrintProfile';
  static const _kFontPkg = null;

  static const IconData profile = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
