/// Flutter icons BluePrintCall
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BluePrintCall
///      fonts:
///       - asset: fonts/BluePrintCall.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BluePrintCall {
  BluePrintCall._();

  static const _kFontFam = 'BluePrintCall';
  static const _kFontPkg = null;

  static const IconData call = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
